### ISSUE TITLE
joining

### ISSUE THREAD

**Issue by nothingismagick** [teamopen-dev/workgroups#9]
Please **add me** to the following workgroups:

- [x] [Organization][wg-organization] - _Organization level day-to-day tasks._
- [x] [Outreach][wg-outreach] - _Reaching out to where Team Open may help._
- [x] [Lifeguard][wg-lifeguard] - _Development of the Lifeguard project itself._
- [x] [Lifeguard Devs][wg-lifeguard-devs] - _People who maintain OSS in the Lifeguard programe._
- [x] [Media][wg-media] - _(Social) media, publication and communication tasks._

  username: nothingismagick
  display: Daniel Thompson-Yvetot

[wg-organization]: https://github.com/teamopen-dev/workgroups/tree/master/workgroups/wg-organization.md
[wg-outreach]: https://github.com/teamopen-dev/workgroups/tree/master/workgroups/wg-outreach.md
[wg-lifeguard]: https://github.com/teamopen-dev/workgroups/tree/master/workgroups/wg-lifeguard.md
[wg-lifeguard-devs]: https://github.com/teamopen-dev/workgroups/tree/master/workgroups/wg-lifeguard-devs.md
[wg-media]: https://github.com/teamopen-dev/workgroups/tree/master/workgroups/wg-media.md

**Comment by Beanow** [comment]
Glad to have you :smile:
Since you're no stranger to the org, we'll be skipping trial and go right to memberships.
I've included the `github, discord` roles for organization as you technically already have these.
Poke me if there's any other roles you're interested in.
